### ISSUE TITLE
Bug on `SliderBtn` with a `Slider` using "contain" option

### ISSUE THREAD

**Issue by antoine4livre** [studiometa/ui#101]
CodePen :
[https://codepen.io/antoine4livre/pen/MWXLKGx?editors=1010](https://codepen.io/antoine4livre/pen/MWXLKGx?editors=1010)

When the last slides are already in the viewport we can click on the "next" button until the last item is "active" but the slider is already in the final position.

**Comment by titouanmathis** [comment]
This is actually not a bug, as the buttons will activate each slide one by one. When the `contain` option is enabled, slider items will be sticked to the right side of the container, but you are still able to navigate between them to activate them. 

We could provide an option to the `SliderBtn` component to adapt this behavior. 

@antoine4livre could you override the `SliderBtn` component in your project to implement this option and test it?
