### ISSUE TITLE
[FigureTwicpics] Add support for local images

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/ui#125]
When working with images on a local environment, TwicPics fails to load the image. 

We could add an option to the component to easily disable the source URL transformation in order to display the original image. 

```html
<figure data-component="FigureTwicpics" data-option-no-transform>
  <img data-src="/image.jpg" /> <!-- <img src="/image.jpg"> -->
</figure>

<figure data-component="FigureTwicpics">
  <img data-src="/image.jpg" /> <!-- <img src="https://cdn.twic.pics/path/image.jpg"> -->
</figure>
```

**Comment by KeziahMoselle** [comment]
I think it should be done with an option on the project's level and not an option for a single image.

That probably requires to extend the `FigureTwicpics` component and overrides a getter depending on the environment to disable the `formatSrc` behavior. 

Thoughts?

**Comment by titouanmathis** [comment]
The option is available for each image, but it can be set by the environment when including the Twig template:

```twig
{% include '@ui/atoms/FigureTwicpics/FigureTwicpics.twig' with {
  attr: {
    data_option_disable: _context.env.is_dev ?? null
  },
} %}
```

This way we can avoid injecting environment variables at build time in our JavaScript files, and drive this feature from the back-end.

The diff for the `FigureTwicpics.ts` file would be simple: 

```diff
diff --git a/packages/ui/atoms/Figure/FigureTwicpics.ts b/packages/ui/atoms/Figure/FigureTwicpics.ts
index 1a0740c..6348d89 100644
--- a/packages/ui/atoms/Figure/FigureTwicpics.ts
+++ b/packages/ui/atoms/Figure/FigureTwicpics.ts
@@ -52,6 +52,7 @@ export class FigureTwicpics<T extends BaseProps = BaseProps> extends Figure<
         type: String,
         default: 'cover',
       },
+      disable: Boolean,
     },
   };
 
@@ -74,7 +75,7 @@ export class FigureTwicpics<T extends BaseProps = BaseProps> extends Figure<
    * Get formattted original source.
    */
   get original() {
-    return this.formatSrc(super.original);
+    return this.$options.disable ? super.original : this.formatSrc(super.original);
   }
 
   /**
```

Maybe the option could be renamed to `devMode` or something easier to understand.

**Comment by KeziahMoselle** [comment]
Got it, looks good to me then 👍 
I'd like to work on this very soon
