### ISSUE TITLE
Generic Image Component

### ISSUE THREAD

**Issue by KeziahMoselle** [studiometa/ui#16]
> Inspired by https://nextjs.org/docs/api-reference/next/image

Often we need to add images to our websites, naturally we add the classic attributes `src`, `alt`, `width`, `height` and `title`.

The thing is that sometimes it is not enough for performance reasons, so we add attributes like `srcset`/`sizes`/`loading="lazy"` or use the other element `<picture>` and their `<source>`.

The issue is that there is a lot of small things to add and think of while working with images, and we repeat a lot of things that can be simplified.

The Twig toolkit could provide a generic image component that simplifies this process and automatically add according attributes and optimize images/SEO automatically based on provided props.

We can provide these props :

- src `<String>` (required)
- alt `<String>` (required)

either :
- size (WordPress size) `<String>` (optional)

or one of these (or the two) :
- height `<Number>` (optional) if missing it will calculate the height based on aspect ratio
- width `<Number>` (optional) if missing it will calculate the width based on aspect ratio

The component will generate either a `<picture>` or `<img>` (I don't really know how this should work but if we want to convert images to .webp or .avif like so : https://timber.github.io/docs/guides/cookbook-images/#using-webp-images it could be interesting)

Question : How can this work if we use an external service like TwicPics ?

**Comment by titouanmathis** [comment]
We now have the `Figure` JS and Twig components, as well as the `FigureTwicPics` JS component 🙂
