### ISSUE TITLE
Add an "Action" component

### ISSUE THREAD

**Issue by antoine4livre** [studiometa/ui#161]
JS component with no twig template to trigger action on another component.

API example :

```html
<button type="button" data-component="Action" data-option-target="Panel" data-option-method="close">Close every panel</button>
```

**Comment by titouanmathis** [comment]
Great idea, 2 points:

- What would the API for passing parameters to the method look like?
- How do I target a specific instance of a Panel?

**Comment by antoine4livre** [comment]
I didn't think that passing parameters to the method would be necessary for the uses I have in mind. 

Any ideas on how to add this?
Maybe like this: `data-option-method="close(true, 'hello')"`
My advice is not to implement it and to handle special cases in the method.

To specify a target, you can add `data-option-selector="#my-component"` to filter instances specified by `data-option-target`.

We could also pass several instance types in the "target" option, separating them with a comma or a space.

```html
<button
  type="button"
  data-component="Action"
  data-option-target="Panel Modal"
  data-option-selector=".can-be-closed"
  data-option-method="close">
  Close every panel & modal with .can-be-closed class
</button>
```

**Comment by antoine4livre** [comment]
@titouanmathis [Here is a first draft](https://ui.studiometa.dev/play/?html=eNqdVMtuGzEMvPsriASBL7GdHnoJnKDPW3sqeiqKQJFom61ekSgnaZB%2F72jXNpwipwpYQKK45HA41NMZSbS%2BOabpuyYLoynUxYemmuLimz56duNhrveyntK96IaeJkTe3LK%2FpOlHnyqT8Z5CcsbX6TkujWq5HNyIrDe1wrGwNypbpj%2BztxeDF5Ezam5sCjlFjgqn91YlxePblLvlRk1Zc%2Ff42rO84hBYN8nBwXZArzhU9mw1Adf0NDzOBrSD2%2FPkmc6eJ5Olk%2B2I9urkfrZqKGkzq7YwR1p5fiBRDnVmgZQL%2FWpVZfW4P%2BbZm4uTa0QDoRxu2Y10hoSkzXNdDLh3jA77fwl9yRqR9GJeAO1Q8XWw%2FYBMtz7Z32QTIETd24mWuSMZ15dUOJDk2gK55FOhKkoGdJ33Hys4YW2FjJMsVazENbEX3FYU4RKxtAoMh4AgISMKVCNOXEPepl0NyEOsYw6mYNbRQBZy18ycvitxlIAkFASbQ7AtzCac012TSjFVLc0RP3CxolBLioQ2mGDTmKE7AWTPOISWDGdaGtoUXl2dnA4d2C82KDAAehoLBRI9XC8X5npOn3pa05RJSgPqkSCJVDgX3nB0XMAWDNvkWwYkBmSwQ1wrH4JZ8X5PL0hotGprMUqxg6dsCg6tzOnzg%2BWsDLargLdkrWF7BMq2LF2y%2BBOV55LEoa%2FoRGcZIKCkbDpXlFYrtMqQ48ql30JoHZY5JldAZd31poX5XhwLqGO3%2F%2B%2FpH9fhDcAspIDZ6U%2BBFlmvuewUe6TrcRrRqP2Q%2Fvg5HRQ9KPtI1aB9FPZgGg3jTMGwXGBMr%2F8C5WOCXA%3D%3D&script=eNqlVMFu2zAMvfsrWCBAHMDzdk6WYd2w4047Fj1oMhNrlUVDooEVrf99tCU5ztYehh4SW%2FTj43s0nk3Xk2d4gi8qYAXao2K87XsY4eSpg%2B3nwENjqENW73%2BFd0xkHwxvD8XS%2BZ0aZV%2FED0ZwhbYqBLjVbMgB%2FmZ0TZjHwVMBEFix0aDJncwZjnMNwKkO97CNTdtqrlE%2FHcI%2BQQBY%2BTPyHn6wN%2B4cQQAyuaXm72pAi5rJX9fH6TIW8tfR4BibcpfYRU%2BYzMUZVWIVl0fg1oR6k9SIvwluTlDeRCw8P8NNgsttLNYW3Zlb%2BHiED1M1Pl9X82CxNfMz%2Bs44eRnl7pAeeOTBu3gas3AVHp0Gcl%2Bt0Q%2BvyN%2FP%2B8wmqmUZr9qxYiO2hgXhibje6NbYxqO7mxjv%2F3UfLp7Dy%2FauXSz9WdNqDxcBie9krKylLON5B8dPeb0btHWnWLcYLkxpcashbxG5iCD%2FTen2SkVuW824i8u%2Bv3Besy68mTk35Pc9ztexEFhKkKTyP%2BPT9yk7miStDh2v4jPnNucjJm2disM8OX8PSvlV0JAeOmGpf1LzKPr%2BAEDkRss%3D), I prepare the PR...

**Comment by titouanmathis** [comment]
I think your implementation is missing an option to configure the type of event triggering the action. Maybe a `data-option-on` could be added? It could be either a single event (`click`) or a list of events (`mouseenter mouseleave`). 

This could then be used on `<form>` elements for example.
