### ISSUE TITLE
Atom Button cannot be set to type submit

### ISSUE THREAD

**Issue by perruche** [studiometa/ui#24]
The type attribute for a `<button>` cannot be set to `type="submit"`, has it is default to `type="button"` when the html tag is `<button>`

```twig
type: tag == 'button' ? 'button' : false,
```

**Comment by titouanmathis** [comment]
This is odd as the `type` property is set for the default attributes, which should be overridden when using the `attr` parameter 🤔 

I will have a look at this.

**Comment by perruche** [comment]
i'm a n***, something was not set correctly on my end
