### ISSUE TITLE
Change ref names to allow multiple open/close triggers

### ISSUE THREAD

**Issue by perruche** [studiometa/ui#45]
## Suggestion
- Update the `refs` name for components with `open|close` behaviors to allow adding multiple `open|close` triggers easily. This is currently working but with a warning `The "close" ref has been found multiple times. Did you forgot to add the [] suffix to its name?` 

## Solution
Switch the declaration from `refs: ['open', 'close']` to refs: `['open[]', 'close[]']` for components like `Modal`, `Panel`

## Questions
- Will this cause breaking change ?
- Should this be the go to way when implementing click behaviors with refs on components ?

**Comment by perruche** [comment]
Yes sure, i'll send a PR. 

Do not have an opinion on refs vs component, you know the inner machine better, so i'll follow what you think is best

**Comment by titouanmathis** [comment]
Fixed in #49 and released in [0.2.9](https://github.com/studiometa/ui/releases/tag/0.2.9).
