### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/ui#69]
Add to the README.md file a "Contributing" section with:

- How to install the project locally
- How to setup a dev environment to work locally
- How to do a pull-request for a bugfix or a feature
- How to do a pull-request for a release or a hotfix

**Comment by KeziahMoselle** [comment]
I think we can close this as this has been done https://ui.studiometa.dev/-/guide/contributing/

**Comment by titouanmathis** [comment]
👍
